AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    auto_snapshot

    Sample SAM Template for auto_snapshot
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10


Resources:

    AutoSnapshotFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: auto_snapshot/
            Handler: app.lambda_handler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ACCESS_KEY: AKIAJGVNTFYHN5EBKQTA
                    SECRET_ACCESS_KEY: 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
                    REGION: ap-northeast-1
            Events:
                AutoSnapshot:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 16 * * ? *)

    DeleteSnapshotFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: delete_snapshot/
            Handler: app.lambda_handler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ACCESS_KEY: AKIAJGVNTFYHN5EBKQTA
                    SECRET_ACCESS_KEY: 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
                    REGION: ap-northeast-1
            Events:
                AutoSnapshot:
                    Type: Schedule
                    Properties:
                        Schedule: cron(30 16 * * ? *)

Outputs:

    AutoSnapshotFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt AutoSnapshotFunction.Arn

    AutoSnapshotFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt AutoSnapshotFunctionRole.Arn

    DeleteSnapshotFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt DeleteSnapshotFunction.Arn

    DeleteSnapshotFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt DeleteSnapshotFunctionRole.Arn